### ISSUE TITLE
Import libsonnet file on windows is not working

### ISSUE THREAD

**Issue by PapaMufflon** [ksonnet/kubecfg#238]
Having a simple libsonnet file:

```
{
    test: "test"
}
```

and an simple jsonnet file:

```
local foo = import "test.libsonnet";

foo
```

When I do `kubecfg.exe show -o yaml test.jsonnet`, I get

```
ERROR Error reading test.jsonnet: RUNTIME ERROR: Could not get candidate URLs for when importing test.libsonnet (import dir is file://C:%5Csrc%5Ctest.jsonnet)
        file://C:%5Csrc%5Ctest.jsonnet:1:13-36       thunk <foo> from <$>
        file://C:%5Csrc%5Ctest.jsonnet:3:1-4 $
        During evaluation
```

**Comment by anguslees** [comment]
The bug is somewhere in https://github.com/ksonnet/kubecfg/blob/6b6a76d1ef6aab0e6a496ac86cea18e6dbfb171b/utils/importer.go#L145 or maybe in the initial construction of the current-directory file URL (https://github.com/ksonnet/kubecfg/blob/master/utils/acquire.go#L159)

I have no idea how file:// URLs are meant to be treated on windows ;)
How does the drive letter get encoded? Which way do the slashes go?

**Comment by PapaMufflon** [comment]
@anguslees I don't know golang, but file://C/src/test.jsonnet should be correct. So basically remove the ':' after the C :)
