### ISSUE TITLE
Add links to http://ksonnet.heptio.com/

### ISSUE THREAD

**Issue by jhermann** [ksonnet/kubecfg#49]
Link your org's and project's "Website" settings to http://ksonnet.heptio.com/ to make things more discoverable.

**Comment by anguslees** [comment]
.. except ksonnet.heptio.com is (a) a heptio-specific site, and (b) doesn't mention `kubecfg`.

Assigning to @hausdorff to sort out the heptio side of things, and what we want to do with ksonnet websites generally (eg ksonnet-lib also doesn't mention kubecfg, and I removed ksonnet-lib from kubecfg's examples some time ago because ksonnet-lib didn't work at the time).

**Comment by jessicayuen** [comment]
This issue was moved to ksonnet/ksonnet#20
