### ISSUE TITLE
`ksonnet version` displaying badly formatted client-go version

### ISSUE THREAD

**Issue by jessicayuen** [ksonnet/kubecfg#92]
```
$ kubecfg version
kubecfg version: (dev build)
jsonnet version: v0.9.4
client-go version: v1.6.8-beta.0+$Format:%h$
```

**Comment by anguslees** [comment]
This is a "feature" of client-go.  In order to get the format to work correctly, it has to be compiled with a git sha, etc provided at link-time.  This didn't make much sense with kubecfg, where a naive version of this would show *kubecfg's* git sha.  We could theoretically dig out client-go's git version from `vendor/vendor.json`, but the ROI seemed tiny, just to avoid the above unexpanded format string, so I didn't bother.

I consider this a bug with the upstream client-go version - suggestions welcome for what we can do at our side that makes sense ...
